allowBuilds:
  '@sentry/cli': set this to true or false
  electron-winstaller: set this to true or false
  msw: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
